// Code generated by entc, DO NOT EDIT.

package ent

import (
	"ent-todo/ent/schema"
	"ent-todo/internal/ent/card"
	"ent-todo/internal/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cardFields := schema.Card{}.Fields()
	_ = cardFields
	// cardDescExpired is the schema descriptor for expired field.
	cardDescExpired := cardFields[0].Descriptor()
	// card.DefaultExpired holds the default value on creation for the expired field.
	card.DefaultExpired = cardDescExpired.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
