// Code generated by entc, DO NOT EDIT.

package internal

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
}
